services:
  db:
    image: postgres:16
    container_name: boardly_postgres
    environment:
      POSTGRES_DB: boardly
      POSTGRES_USER: boardly_user
      POSTGRES_PASSWORD: boardly_password000
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: boardly_redis
    restart: unless-stopped

  backend:
    build:
      context: ./apps/backend
    container_name: boardly_backend
    ports:
      - "8001:8000"
    volumes:
      - ./apps/backend:/app
    env_file:
      - ./apps/backend/.env
    depends_on:
      - db
      - redis
    restart: unless-stopped

  frontend:
    build:
      context: ./apps/frontend
    container_name: boardly_frontend
    ports:
      - "80:80"
    env_file:
      - ./apps/frontend/.env
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data: