services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: boardly_backend
    ports:
      - "8001:8000"
    volumes:
      - ./apps/backend:/app
    env_file:
      - ./apps/backend/.env

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    container_name: boardly_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    env_file:
      - ./apps/frontend/.env
    depends_on:
      - backend
