"""add board lists

Revision ID: 0182aae70639
Revises: 8f412a6c11e6
Create Date: 2026-05-08 09:26:52.860996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0182aae70639'
down_revision = '8f412a6c11e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_lists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('board_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('board_lists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_board_lists_board_id'), ['board_id'], unique=False)
        batch_op.create_index('ix_board_lists_board_position', ['board_id', 'position'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board_lists', schema=None) as batch_op:
        batch_op.drop_index('ix_board_lists_board_position')
        batch_op.drop_index(batch_op.f('ix_board_lists_board_id'))

    op.drop_table('board_lists')
    # ### end Alembic commands ###
