"""refine board member indexes

Revision ID: 0e2d3b2bb323
Revises: 27db4c8ae97b
Create Date: 2026-05-06 18:31:56.402254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e2d3b2bb323'
down_revision = '27db4c8ae97b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_board_members_board_id'))
        batch_op.drop_index(batch_op.f('ix_board_members_user_id'))
        batch_op.create_index('ix_board_members_board_user', ['board_id', 'user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board_members', schema=None) as batch_op:
        batch_op.drop_index('ix_board_members_board_user')
        batch_op.create_index(batch_op.f('ix_board_members_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_board_members_board_id'), ['board_id'], unique=False)

    # ### end Alembic commands ###
