"""add board background color and profile endpoints

Revision ID: 1314fc51c492
Revises: 5c56525d7504
Create Date: 2026-05-12 18:49:24.781141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1314fc51c492'
down_revision = '5c56525d7504'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('background_color', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boards', schema=None) as batch_op:
        batch_op.drop_column('background_color')

    # ### end Alembic commands ###
