"""add card due dates assignees and invitations

Revision ID: 19d5fa613a3e
Revises: 0e3e415b4b10
Create Date: 2026-05-08 13:14:44.023622

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '19d5fa613a3e'
down_revision = '0e3e415b4b10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'board_invitations',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('board_id', sa.UUID(), nullable=False),
        sa.Column('invited_by_id', sa.UUID(), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),

        sa.Column(
            'role',
            postgresql.ENUM(
                'owner',
                'admin',
                'editor',
                'viewer',
                name='boardrole',
                create_type=False
            ),
            nullable=False
        ),

        sa.Column('status', sa.String(length=30), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),

        sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['invited_by_id'], ['users.id'], ondelete='CASCADE'),

        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('board_id', 'email', name='uq_board_invitation_email')
    )

    with op.batch_alter_table('board_invitations', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_board_invitations_board_id'),
            ['board_id'],
            unique=False
        )

        batch_op.create_index(
            batch_op.f('ix_board_invitations_email'),
            ['email'],
            unique=False
        )

    op.create_table(
        'card_assignees',
        sa.Column('card_id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),

        sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),

        sa.PrimaryKeyConstraint('card_id', 'user_id')
    )

    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('due_date', sa.DateTime(timezone=True), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_column('due_date')

    op.drop_table('card_assignees')

    with op.batch_alter_table('board_invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_board_invitations_email'))
        batch_op.drop_index(batch_op.f('ix_board_invitations_board_id'))

    op.drop_table('board_invitations')

    # ### end Alembic commands ###