"""add board cascade deletes

Revision ID: 38432bf52dea
Revises: 1314fc51c492
Create Date: 2026-05-13 19:12:34.671611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38432bf52dea'
down_revision = '1314fc51c492'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board_members', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('board_members_board_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('board_members_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'boards', ['board_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('boards', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('boards_owner_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['owner_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boards', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('boards_owner_id_fkey'), 'users', ['owner_id'], ['id'])

    with op.batch_alter_table('board_members', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('board_members_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('board_members_board_id_fkey'), 'boards', ['board_id'], ['id'])

    # ### end Alembic commands ###
