"""hash verification and invitation tokens

Revision ID: 5c56525d7504
Revises: 9b409e131615
Create Date: 2026-05-12 13:26:11.949190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c56525d7504'
down_revision = '9b409e131615'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board_invitations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_hash', sa.String(length=64), nullable=False))
        batch_op.drop_index(batch_op.f('ix_board_invitations_token'))
        batch_op.create_index(batch_op.f('ix_board_invitations_token_hash'), ['token_hash'], unique=True)
        batch_op.drop_column('token')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verification_token_hash', sa.String(length=64), nullable=True))
        batch_op.drop_index(batch_op.f('ix_users_email_verification_token'))
        batch_op.create_index(batch_op.f('ix_users_email_verification_token_hash'), ['email_verification_token_hash'], unique=True)
        batch_op.drop_column('email_verification_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verification_token', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_users_email_verification_token_hash'))
        batch_op.create_index(batch_op.f('ix_users_email_verification_token'), ['email_verification_token'], unique=True)
        batch_op.drop_column('email_verification_token_hash')

    with op.batch_alter_table('board_invitations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_board_invitations_token_hash'))
        batch_op.create_index(batch_op.f('ix_board_invitations_token'), ['token'], unique=True)
        batch_op.drop_column('token_hash')

    # ### end Alembic commands ###
