"""add boards crud and board memberships

Revision ID: 8f412a6c11e6
Revises: c364260252df
Create Date: 2026-05-08 09:10:25.743869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f412a6c11e6'
down_revision = 'c364260252df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board_members', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('board_members_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('board_members_board_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'boards', ['board_id'], ['id'])

    with op.batch_alter_table('boards', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('boards_owner_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boards', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('boards_owner_id_fkey'), 'users', ['owner_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('board_members', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('board_members_board_id_fkey'), 'boards', ['board_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('board_members_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
