"""add email verification to users

Revision ID: 9b409e131615
Revises: cf89589ed10a
Create Date: 2026-05-10 20:14:02.712044

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b409e131615'
down_revision = 'cf89589ed10a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:

        batch_op.add_column(
            sa.Column(
                'is_email_verified',
                sa.Boolean(),
                nullable=False,
                server_default=sa.text('false')
            )
        )

        batch_op.add_column(
            sa.Column(
                'email_verification_token',
                sa.UUID(),
                nullable=True
            )
        )

        batch_op.add_column(
            sa.Column(
                'email_verification_expires_at',
                sa.DateTime(timezone=True),
                nullable=True
            )
        )

        batch_op.create_index(
            batch_op.f('ix_users_email_verification_token'),
            ['email_verification_token'],
            unique=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(
            batch_op.f('ix_users_email_verification_token')
        )

        batch_op.drop_column('email_verification_expires_at')
        batch_op.drop_column('email_verification_token')
        batch_op.drop_column('is_email_verified')

    # ### end Alembic commands ###